### ISSUE TITLE
Feature request: integration with Git Graph

### ISSUE THREAD

**Issue by yushiyangk** [jacekkopecky/vscode-whole-diff#7]
[Git Graph extension here](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)

Honestly, this is the one missing feature that would make Git Graph perfect for me.

I understand if this is not a priority, especially if you don't use the extension, but just thought I'd put it out there for now.

I could try to do it myself but I've never worked on VSCode extensions before.

**Comment by jacekkopecky** [comment]
Thanks @yushiyangk for the suggestion. Indeed I use Git Graph as well, and I've looked at putting Whole Diff there, but I'd need to work with Git Graph's author on that because it doesn't provide easy extension points as far as I could find.

Instead I have a workaround that works well enough for me: 

1. bind the command `whole-diff.showWholeDiffByShaImmediate` to a keyboard shortcut like `cmd+shift+d`
2. in Git Graph, double click the commit hash, then press `cmd+c` to copy and `cmd+shift+d` to show the diff.

If you find that Git Graph does have extension points, I can look at it; or better yet, I'll be happy to review a PR. 8-)

But the VS Code team are working on [a multi-file diff viewer](https://github.com/microsoft/vscode/pull/197652) so it's possible that Whole Diff will soon be obsolete (if they do a good job and it's better for me than my own extension).

**Comment by yushiyangk** [comment]
Thanks for linking that PR, that looks pretty interesting!

**Comment by jacekkopecky** [comment]
Closing as probably no longer needed; anyway, PRs are welcome.
